name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Atualiza diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessário para commitar no repo
    env:
      ACTIONS_STEP_DEBUG: true  # Ativa debug detalhado nos passos da Action
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: matheuscamarques

          output_action: commit
          committer_branch: main

          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          config_display: large

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_community: yes
          plugin_community_roles: admin, contributor, member

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12

          plugin_stars: yes
          plugin_topics: yes

          plugin_traffic: yes

          plugin_people: yes
          plugin_people_types: contributors, followers
          plugin_people_limit: 24

          plugin_gists: yes

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://medium.com/@matheuscamarques

          config_twemoji: yes
