name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Atualiza diariamente à meia-noite UTC
  workflow_dispatch:              # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # =========================================
          # 🧱 BASE
          # =========================================
          user: matheuscamarques
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          config_display: large

          # =========================================
          # 📅 CALENDÁRIO DE ATIVIDADE
          # =========================================
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # =========================================
          # 💬 INTERAÇÕES COMUNIDADE
          # =========================================
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_community: yes
          plugin_community_roles: admin, contributor, member

          # =========================================
          # 🧠 LINGUAGENS
          # =========================================
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12

          # =========================================
          # ⭐ ESTATÍSTICAS DE STARS E TOPICS
          # =========================================
          plugin_stars: yes
          plugin_topics: yes

          # =========================================
          # 🌐 TRÁFEGO DE VISITAS
          # =========================================
          plugin_traffic: yes

          # =========================================
          # 🤝 COLABORAÇÃO COM PESSOAS
          # =========================================
          plugin_people: yes
          plugin_people_types: contributors, followers
          plugin_people_limit: 24

          # =========================================
          # 📎 GISTS
          # =========================================
          plugin_gists: yes

          # =========================================
          # 📄 PÁGINAS PESSOAIS (SPEED)
          # =========================================
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://matheuscamarques.dev

          # =========================================
          # 🎨 TEMA (opcional)
          # =========================================
          config_twemoji: yes
